version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    tty: true
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  db:
    build:
      context: .
      dockerfile: ./dockerfiles/postgresql/Dockerfile
      args:
        - DB_LANG=ja_JP
    volumes:
      - pgsqldb:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

volumes:
  pgsqldb:
    driver: local
  bundle:
    driver: local
