version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    tty: true
    environment:
      # - POSTGRES_USER
      # - POSTGRES_PASSWORD
      - MYSQL_ROOT_PASSWORD
  db:
    # image: postgres:10.7-alpine
    # volumes:
    #   - pgsqldb:/var/lib/postgresql/data
    # environment:
    #   - POSTGRES_USER
    #   - POSTGRES_PASSWORD
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysqldb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD


volumes:
  # pgsqldb:
  #   driver: local
  mysqldb:
    driver: local
  bundle:
    driver: local
