version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    tty: true
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  db:
    # image: postgres:10.7-alpine
    image: mysql:8.0.17
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      # - pgsqldb:/var/lib/postgresql/data
      - mysqldb:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      # - POSTGRES_USER
      # - POSTGRES_PASSWORD

volumes:
  # pgsqldb:
  #   driver: local
  mysqldb:
    driver: local
  bundle:
    driver: local
