version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    tty: true
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
  db:
    build:
      context: .
      dockerfile: dockerfiles/mysql/Dockerfile
      args:
        - DB_LANG=ja_JP
    command: --default-authentication-plugin=mysql_native_password --lc_messages_dir=/usr/share/mysql-8.0 --lc_messages=ja_JP
    # command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysqldb:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

volumes:
  mysqldb:
    driver: local
  bundle:
    driver: local
