version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    tty: true
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - "SELENIUM_DRIVER_URL=http://chromedriver:4444"
  chromedriver:
    image: selenoid/chrome
    ports:
      - "4444:4444"
  db:
    image: postgres:10.7-alpine
    volumes:
      - pgsqldb:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

volumes:
  pgsqldb:
    driver: local
  bundle:
    driver: local
