default_postgresql: &default_postgresql
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: <%= ENV.fetch("POSTGRES_USER") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>

default_mysql: &default_mysql
  adapter: mysql2
  encoding: utf8mb4
  username: root
  password:
  host: mysql

development:
  backbone:
    <<: *default_postgresql
    database: backbone_development
  library:
    <<: *default_mysql
    database: library_development
    migrations_paths: db/library_migrate

test:
  backbone:
    <<: *default_postgresql
    database: backbone_test
  library:
    <<: *default_mysql
    database: library_test
    migrations_paths: db/library_migrate

production:
  backbone:
    <<: *default_postgresql
    database: backbone_production
    username: backbone
    password: <%= ENV['BACKBONE_DATABASE_PASSWORD'] %>
  library:
    <<: *default_mysql
    database: library_production
    migrations_paths: db/library_migrate
    username: library
    password: <%= ENV['LIBRARY_DATABASE_PASSWORD'] %>
